language: node_js
node_js:
- 0.12.7
- iojs
branches:
  only:
  - master
before_install: npm install -g grunt-cli
before_script:
- npm install -g bower
- npm install -g grunt
- bower install
deploy:
  provider: heroku
  api_key:
    secure: YmYw3F9I1xA9k/ZPeee7yWDlfawVBqgNFG5j/YWu0GeJXX6ApK9zShLOLo/Fgovj2w3Y5FgQGCFjQgs3erOdA7mS3uFSU+ZWv6g0rQrb6exK9hluGLtieVFsIBUCX4Z+BIhJGE3IABeoh1CZnUsA5xYlHg5Yzl/MKn7Dq0zeFpd145OQchIZ/MPqV5dwqFrMCQhS+8H9lCNdufKhOj/AYQfuXhjXZrZ15AWthaR+yLr6ZjF+Vdn3ki/hFwhyQyxRNJe8RrxTZATtW/b4exCPq6hpcl9hLM/xlHCkiTtlk2Z1TIMBQdA+ziaiWHUQr0OYlM50E2OxFLZXR12maU5sbHv+0wRkuKHI4cg6J9h1MaHrNe8gdlH9RWO/GaqWJ2aQaG3zr29bbuCEcSw8T9mFOrMpiizjxEO36d8iWeZRcKmI8X4anpfM1k3HbTO9Gkl3lNA2Gxclu5iFWcxoZQvhoV+XKIKNQ15IYRoC3XIuWked6mA+RjWBpH2kCxyh+1cceQCXxnrjTj3OO/ZJvmeNh7kjt2PVYXsao+T2M+hV5b5TBLYSc1Nrj6eXQYJu7HAPcFIvsAkpW9G5XmA6qB3kQvcS55XnZN9gXuRZdbMD2J0cYB75qAfLiC6OS91SoBSGxfGXySBIeJddaYqaiQKQjQa95N8PTJC4is9SY5Tt3Vo=
  app: ohno
