language: node_js
node_js:
- 0.12.7
- iojs
branches:
  only:
  - master
before_install: npm install -g grunt-cli
before_script:
- npm install -g bower
- npm install -g grunt
- bower install
deploy:
  provider: heroku
  api_key:
    secure: J35rMHTqxykdZ9zo3Tp8Qm+FabrUYbvPQ5w9H1TEl1LS2Nhu+ZAsRtnoAl0xCpr3nHGEDOQ6i8pGNsb7mitQVOV+x347wU163WnYMDf3TPFJk+ibUc7Dc8+pJuTZiBMFQniOApIgElFB+GbqKlnbf7roVZIiu2/qj2tlB2GEb3NKq7YM75Lt7lSKbB2NONDqlCZof6YBXklsdcysMeOD1ay9AcX114+2V/glDk++pf/VobIb/xjaKdCJp3HcbsOhFMRr09XNw7dJ0cN0Er0r80BrvPL6n0zFaMOow0MWwMclPcY8tNiCl/rPMUREXi6OXjMdr+6fLxO4gL2Wzdsd1fe+REQY0KeMv2PNxipRzKn/nYOwthZKYINhpyJUxhFL+HPMWb2KvdiZcPDRObKkpLX8BZlTgz+EV3sTHaAQ0fB6/W7HpQHFMs0ZAsvGYw1IzOZzG4TchHzYSegGBkou3HgpjRWrWTSRodPu98dHu7tFjwJGzL/KmQ+58JOiCN0IPOLWH7GhLmv2mQc1Mae5R50pYdLlCYyINX75bFDZj5vl4LmTuLhM0kiStBmadO4Y9SmvVJZGG5crczoZV9Qd4emsC4PrayzOKMc4wT1RPWC6wKAD3meUUGTNT9RE6OGZqRgcehsOD+Oiwva0FySMOOiGo4d/QB8Nor2doqP4Ltc=
  app: ohno
